---
show_empty_channels: false
mark_on_open: false
down_on_mark: true
app_title: "TYT"
update_at_start: true
sort_by_tag: false
video_player: umpv
default_sorting_method: UnseenDate
spacer: " | "
notify_with: "dunstify"
