name: Build and Release Rust Project

on:
  push:
    tags:
      - '*' # Trigger on all tag pushes

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      # prepare nix and devenv
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the Rust project
      - name: Build project
        run: |
          cargo build --release

      # Optionally compress the build output
      - name: Compress build output
        run: |
          tar -czvf tyt-linux.tar.gz -C target/release/ tyt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tyt-linux.tar.gz
          fail_on_unmatched_files: true

